<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>change-password-error</name>
   <tag></tag>
   <elementGuidId>752bd75a-d15f-4046-868d-14f55a3780e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='change-password']/div/div[2]/form/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.bg-card.card-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>14b363bf-eea0-4932-a3ba-1ea7e8faebfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body bg-card card-password</value>
      <webElementGuid>6d7da23c-49a1-40cf-b814-e691d829d76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters</value>
      <webElementGuid>9f4a0954-cb05-469e-a51c-c0b3fc738286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;change-password&quot;)/div[@class=&quot;row wrapper-login layout&quot;]/div[@class=&quot;col-12 mb-5&quot;]/form[1]/div[@class=&quot;group mb-3&quot;]/div[@class=&quot;card bg-message&quot;]/div[@class=&quot;card-body bg-card card-password&quot;]</value>
      <webElementGuid>926573e0-e352-4e02-86a3-39936288875d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='change-password']/div/div[2]/form/div[2]/div/div</value>
      <webElementGuid>3afdb61e-ac4d-482d-b251-f59603a3214a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Set your new password'])[1]/following::div[3]</value>
      <webElementGuid>91ee9fa8-5d97-4893-bf47-f8b848cd17e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[2]/following::div[5]</value>
      <webElementGuid>f3ccf4a0-2caa-49ae-8904-a837e401d3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>84fe704e-a58d-4777-b17b-61071650cc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters' or . = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters')]</value>
      <webElementGuid>d347a031-62b6-4a28-a041-76de502e7019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
