<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modal-success</name>
   <tag></tag>
   <elementGuidId>48022e8a-7622-472d-9779-f57c65b61986</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bc6b1713-4232-44d1-8cbd-ca77c3fe04e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>71072d41-2f4a-4bc4-ad7f-8ccd3bf88153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>5eed1b6d-cc90-42b2-8973-7fadfe8c3eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>410979bf-6467-4e34-94c0-520634c141d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-success&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]/img[@class=&quot;mx-auto&quot;]</value>
      <webElementGuid>a57aa1b1-bf8c-4b36-b002-bf4eb6896893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-success']/div/div/div[2]/img</value>
      <webElementGuid>d15192e6-2291-42c0-955b-f6fb815c11a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>fbb63fe7-75ba-4222-acdf-b68c4d3171b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg']</value>
      <webElementGuid>b3699c6e-884c-4fd0-996b-a96caa06c7e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
