<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>resetPassword</name>
   <tag></tag>
   <elementGuidId>24f93ada-46d8-43d9-9536-2ed1ea04811c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='resetPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#resetPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4ad5028-63cd-4dfe-8e3d-bd389afa837e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>resetPassword</value>
      <webElementGuid>3460a583-f575-4f5e-bcc8-b46971fe32f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-12 mb-5</value>
      <webElementGuid>383d5cc6-04d1-4fbc-ab3d-a6f62a4396c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Email   Next</value>
      <webElementGuid>fdcd24cb-3f2d-4bfa-8c00-1d2a19d6bdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;resetPassword&quot;)</value>
      <webElementGuid>1f24adef-0787-48a1-b77a-d4caa129f525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='resetPassword']</value>
      <webElementGuid>37e3e35d-614e-4062-a352-e122d1d80d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[2]/following::div[1]</value>
      <webElementGuid>acfbf83a-e3d7-4764-8b48-e061ce8c4fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>88e1e51a-865a-4b41-bad3-ab4e267e2f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'resetPassword' and (text() = '  Email   Next' or . = '  Email   Next')]</value>
      <webElementGuid>e1299e98-393d-4c0a-9e89-7278fa648c27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
