<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uss-password-reset-next-button</name>
   <tag></tag>
   <elementGuidId>9c5ab4fc-6e6a-40d9-8c59-73367e3d0d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='uss-password-reset-next-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-password-reset-next-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>07cb8f04-0869-4200-b5c3-45f6b783c5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-password-reset-next-button</value>
      <webElementGuid>762a8aa4-3085-4788-8c65-56d736ec929d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2f481a9b-1b6c-4b22-86eb-ee9c7488ae7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary w-100  border border-1 py-2</value>
      <webElementGuid>c5dc3271-aa33-49d0-8f74-b3bac07cd71c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>9d0e6cbf-7e09-468c-9012-dbcb5e1d8046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-password-reset-next-button&quot;)</value>
      <webElementGuid>0a6ac033-62fb-479f-8caa-0691712e7bba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='uss-password-reset-next-button']</value>
      <webElementGuid>73671eac-067e-4e26-a101-a9d7f5326e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='resetPassword']/form/div[2]/button</value>
      <webElementGuid>88b49f84-979b-42d2-a0f2-bb591376d5b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>7e84e6d7-8961-430e-9858-287ce211b392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password'])[2]/following::button[1]</value>
      <webElementGuid>16e93212-b232-4765-805a-380a16386d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'uss-password-reset-next-button', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>cd78c09c-e7a5-4a21-9632-defd7bf0a230</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next']/parent::*</value>
      <webElementGuid>a670e9b7-bedf-4c2e-a376-e7a922cdf7d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>c47ffad3-a99b-478c-b9fa-61854955046a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'uss-password-reset-next-button' and @type = 'submit' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>e4e17dd7-f2bb-453b-8491-6b127b6822ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
