<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uss-password-reset-brand-image</name>
   <tag></tag>
   <elementGuidId>337d5562-73f7-40ee-8a65-80100c7d2371</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='uss-password-reset-brand-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-password-reset-brand-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>705f7a1a-a94b-488e-a02f-1d971365dbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-password-reset-brand-image</value>
      <webElementGuid>9e92e4ed-c202-4b4e-8e71-b929058731b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo-mh360.png</value>
      <webElementGuid>281efe0c-1ff4-40be-bee1-e5ed3b174dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-mh360 mb-4 mt-4</value>
      <webElementGuid>e72e8881-d77a-4c7a-b25a-b3a9dc12ab0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-password-reset-brand-image&quot;)</value>
      <webElementGuid>58593a6c-e71f-45cf-ac5a-a14a71edc711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='uss-password-reset-brand-image']</value>
      <webElementGuid>817d71be-c41b-4c31-b224-0818eb3953dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d4776380-67f6-49e9-8ae2-16f9a6dbc297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'uss-password-reset-brand-image' and @src = 'assets/images/logo-mh360.png']</value>
      <webElementGuid>358d779a-375d-489b-98d8-75255ec0ff5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
