<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TCF_W_message-error-Incorrect-otp</name>
   <tag></tag>
   <elementGuidId>cea65017-0bf9-479b-83c7-2e39e407f042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='MH360SmsloginForm']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mb-3 > div.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f96ff40e-f592-48c6-a5ea-492b8d67023e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>e802a35a-5de2-4018-9b80-1165fe8b65a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	Incorrect SMS OTP, please try again. 
                                                        </value>
      <webElementGuid>20e92f73-e047-4cb8-9f3c-9ff01718436a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm&quot;)/div[@class=&quot;mb-3&quot;]/div[@class=&quot;text-center&quot;]</value>
      <webElementGuid>d1eb4671-c41e-46cf-80bd-72e288701b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div/div</value>
      <webElementGuid>265868c1-5c29-4144-a30b-bb99b7a7151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[3]</value>
      <webElementGuid>17e7b062-eed8-4a1f-b589-5b311c18f324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/preceding::div[1]</value>
      <webElementGuid>734937c9-d4bb-460f-bc74-5e7a7b3b1327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>b86d991f-fc28-484a-aa94-3ccf0238ede7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '	Incorrect SMS OTP, please try again. 
                                                        ' or . = '	Incorrect SMS OTP, please try again. 
                                                        ')]</value>
      <webElementGuid>4a39dae2-a357-4280-930c-55d88eb48fcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
