<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TCF_W_div_otp-field</name>
   <tag></tag>
   <elementGuidId>b2e68903-0032-4ef9-b15d-0f5923b1dda0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OTPInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48edb6d8-0c21-436d-8c7c-44eabf8ca040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>digit-group-single flex justify-center pt-5 text-center</value>
      <webElementGuid>97a753ab-af32-4368-8218-427aef72372c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPInput</value>
      <webElementGuid>aeea892a-0f9e-44f6-af2e-b71498dd78d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPInput&quot;)</value>
      <webElementGuid>7593442d-e039-47ea-9eb7-bd922d1c7fe2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='OTPInput']</value>
      <webElementGuid>6f48b1e9-f94a-45c3-8bd7-15ed06d80db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div/div[3]</value>
      <webElementGuid>df962daf-9c5e-476d-a859-3f16777561ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/following::div[1]</value>
      <webElementGuid>40ab4cbc-9004-4aef-b1e8-f86aebaefab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[6]</value>
      <webElementGuid>e86c1c32-8693-4e02-ba41-bf116156c93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend the OTP to my mobile phone in 38'])[1]/preceding::div[1]</value>
      <webElementGuid>cc5bb507-33d4-46e3-8e1d-b5edd55afdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send OTP to my email'])[1]/preceding::div[2]</value>
      <webElementGuid>1d6704c4-3c40-4683-8f60-b7cd2364ea34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>83e85a94-011f-48d3-8c97-26624685859c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'OTPInput']</value>
      <webElementGuid>27a8c257-7126-420b-96f4-4dbeb4d51abf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
