<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_div-otp-field</name>
   <tag></tag>
   <elementGuidId>e23f3c08-37ac-4154-90cd-a994b8ac680f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OTPInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d5053c1-16d3-4c57-bdca-f8dca4d389d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>digit-group-single flex justify-center pt-5 text-center</value>
      <webElementGuid>affb8da4-e8a3-4ef3-a14e-0fc44fcebe46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPInput</value>
      <webElementGuid>e329be84-1493-4e92-b865-b232beba412d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPInput&quot;)</value>
      <webElementGuid>e13537b5-d3f4-4a0a-a1ea-084c63499a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='OTPInput']</value>
      <webElementGuid>dc0e5a5f-5e93-47e0-a16c-3a9e97bc5528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div/div[3]</value>
      <webElementGuid>fcf3c217-f25e-4a3c-b9ea-87d176c6b4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[5]</value>
      <webElementGuid>578b7477-4832-46e5-a53e-a0f9a4073ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend the OTP to my email in 04'])[1]/preceding::div[1]</value>
      <webElementGuid>13861086-dbaf-48d5-aaf5-96ea405888cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send OTP to my email'])[1]/preceding::div[2]</value>
      <webElementGuid>83ee4b23-b23c-4314-add8-bef9c62691aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>a7569c51-b07c-4db2-9d27-36c88fee71b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'OTPInput']</value>
      <webElementGuid>dace0bd8-9ab0-4322-80c7-8077f88bfa34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
