<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Email_otp-mh360-image</name>
   <tag></tag>
   <elementGuidId>dd733df5-88b4-4001-a08d-430cadad10af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='login-email-otp-mh360-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-email-otp-mh360-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7f56b312-d327-44d2-83c8-f98644c2756a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-email-otp-mh360-image</value>
      <webElementGuid>64ac5575-766d-46a1-8b66-b3841d618b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/oxauth/ext/resources/images/logo-mh360.png</value>
      <webElementGuid>65546484-8d17-40b6-9561-43b810420f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>88e02a81-be35-4d85-a9fd-06c8380e59ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4</value>
      <webElementGuid>7c7ba7aa-9feb-40ac-9f5e-da04d129eb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-email-otp-mh360-image&quot;)</value>
      <webElementGuid>8767ebdc-9b0d-462e-bf6d-2e5b4a103695</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='login-email-otp-mh360-image']</value>
      <webElementGuid>43112457-5cab-481a-8406-6703bb851b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>472fb0e9-5429-4ad6-8f9d-00a99b929493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'login-email-otp-mh360-image' and @src = '/oxauth/ext/resources/images/logo-mh360.png']</value>
      <webElementGuid>43d6d29d-1078-411a-970a-4ec51cf156a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
