<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Enter your OTP_login-otp-mh360-image</name>
   <tag></tag>
   <elementGuidId>4a13b12b-21cc-4475-be21-b4e84d905a70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-otp-mh360-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>255c2c12-ba8a-4dc1-8324-994ffae9c667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-otp-mh360-image</value>
      <webElementGuid>9e40aeff-2d82-4bf6-a979-1bf25856f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/oxauth/ext/resources/images/logo-mh360.png</value>
      <webElementGuid>636d6c3e-4ecb-4281-a8ff-64263507d3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>fdd253e1-e435-4149-a196-45a67a7a68b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-4</value>
      <webElementGuid>4582e2f5-3802-4cef-add0-d7adf36f319d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-otp-mh360-image&quot;)</value>
      <webElementGuid>a2c33930-e64e-496a-a488-8a3cd7ad0630</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='login-otp-mh360-image']</value>
      <webElementGuid>75c2459c-2a14-4d64-b6a6-cb65398a6e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>8e23aa49-d7dc-4acf-9755-36eae3e16101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'login-otp-mh360-image' and @src = '/oxauth/ext/resources/images/logo-mh360.png']</value>
      <webElementGuid>6952a8cc-1b53-4a72-906a-0abb4ccfbe66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
