<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_If you did not receive an OTP email i_358944</name>
   <tag></tag>
   <elementGuidId>213978e5-c18c-48cf-a9b1-2b7c542748c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b864a8f-e3fa-4e4c-ac78-d5ebda6dd080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>6c40679d-831f-4587-a240-4564c51acfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>064aa0b4-bed2-415f-b3de-2e250d65e921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>3962c457-540b-4505-887c-7f353a9d1710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>be736a60-3e3a-4f43-b250-91b7189d983a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary text-white</value>
      <webElementGuid>f6c2a6fa-d40f-4058-8ea4-7e308b423a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm:submitOTPButton&quot;)</value>
      <webElementGuid>83d06afd-e856-4f71-a3f4-d9f37d49f1c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>7ebb5b90-6dbb-4d56-bf9f-c91537734d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div[2]/div[3]/input</value>
      <webElementGuid>11d3f8c6-5f00-497d-afb8-1aa4ff2a5a7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>23ac2613-2c13-401e-ac62-c239b07b0d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MH360SmsloginForm:submitOTPButton' and @type = 'submit' and @name = 'MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>7086dc1b-8cd0-4d5c-971f-351be7125f9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
