<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Incorrect Email OTP, please try again</name>
   <tag></tag>
   <elementGuidId>1c5463ea-2260-4dd8-859c-eac7f29631e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::li[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.errormsg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a7ba0b96-8c26-4082-8167-5ad988303c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>errormsg</value>
      <webElementGuid>94b2b624-556b-48bb-b792-7b353667e6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>	Incorrect Email OTP, please try again. </value>
      <webElementGuid>4bb10776-393a-4bc4-9917-ef618990d30a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm&quot;)/div[@class=&quot;mb-3&quot;]/div[@class=&quot;text-center&quot;]/ul[@class=&quot;message text-center&quot;]/li[@class=&quot;errormsg&quot;]</value>
      <webElementGuid>5a45d339-df9c-41ee-9edd-b8b747c5d9da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div/div/ul/li</value>
      <webElementGuid>1918054d-4453-48e0-a1f4-ef5a83a08b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::li[1]</value>
      <webElementGuid>6d0ec67a-1ff3-4f33-9ec5-a7c42afd81e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend the OTP to my email in 18'])[1]/preceding::li[1]</value>
      <webElementGuid>09d79872-538d-46e0-a8b9-f40f033ad067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incorrect Email OTP, please try again.']/parent::*</value>
      <webElementGuid>6b2bd6e5-ae1e-4908-8532-2aa5181e4eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>0b54248c-d228-4d53-b81a-8398d07a691e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '	Incorrect Email OTP, please try again. ' or . = '	Incorrect Email OTP, please try again. ')]</value>
      <webElementGuid>aea3fee5-466a-43f2-9430-60607a54248c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
