<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SendEmail_OTP-to-my-email-link</name>
   <tag></tag>
   <elementGuidId>9f33d63f-dce0-4512-b254-0188173a70da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='sendEmailOTP']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sendEmailOTP</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>62ebedc4-16f1-4a86-9033-44a756b380a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dh-link text-center text-16px</value>
      <webElementGuid>8557bf7c-143f-4b65-a101-84118582d31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendEmailOTP</value>
      <webElementGuid>ac3dc147-d3d6-44af-817d-89defd035275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Send OTP to my email</value>
      <webElementGuid>40b4c000-1418-4bc3-bee7-7ca0ca30c957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sendEmailOTP&quot;)</value>
      <webElementGuid>aab1ec4f-1637-43ea-b5a1-b003203e9b51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='sendEmailOTP']</value>
      <webElementGuid>fa56775e-23ce-47f0-ac43-d96b71f2a0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='showEmailLink']/a</value>
      <webElementGuid>2da23c0d-5d7a-4df8-be8f-e918b6af027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Send OTP to my email')]</value>
      <webElementGuid>4d23f399-9ccf-4633-9705-0b9cbceb78ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend the OTP to my mobile phone in 43'])[1]/following::a[1]</value>
      <webElementGuid>0f8352a8-db83-4c86-b7d6-2ca7c08a1768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/following::a[2]</value>
      <webElementGuid>5fb34c96-c2de-4b45-b64e-9709906a2761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you did not receive an OTP email in your inbox, please check your spam or junk folder.'])[1]/preceding::a[1]</value>
      <webElementGuid>3504b8fe-84b9-4d13-b8df-e13be401915d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login Successful'])[1]/preceding::a[1]</value>
      <webElementGuid>e558345b-ddd1-4a08-9212-a1b6805e8065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Send OTP to my email']/parent::*</value>
      <webElementGuid>2cfc04b6-e29d-4725-9f0e-12b428f6dd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
      <webElementGuid>2fffb994-7f95-495f-9bfc-e547def55320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'sendEmailOTP' and (text() = 'Send OTP to my email' or . = 'Send OTP to my email')]</value>
      <webElementGuid>cc8d20bb-ca10-4473-8425-2aa8af65f346</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
