<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitOTPButton-TC-PR</name>
   <tag></tag>
   <elementGuidId>7db51a0c-2808-42f2-a776-a99d0e94ef1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf338ec1-3ded-4312-8918-fc06d06046ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>d357ef8f-7c2c-4e26-bb28-5bc6cb58b26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>73a8e891-df39-41ce-bf09-112dbca3a7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>e66e85d3-a23b-4129-963f-e8fe21741abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>b4abebb7-a7e6-4347-8655-0c9d640997cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary text-white</value>
      <webElementGuid>a92bc634-61e8-4727-8a7a-5509b923451f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm:submitOTPButton&quot;)</value>
      <webElementGuid>faba1afb-6cec-48c7-b5b5-182f9c993b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>a67f0ad2-8edf-4c70-bed5-40b880de7fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div[2]/div[3]/input</value>
      <webElementGuid>f1184756-28dc-4050-b9de-c056e8974ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>22c3f300-0915-441c-8d10-76cab7043935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MH360SmsloginForm:submitOTPButton' and @type = 'submit' and @name = 'MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>430a96f5-cd1d-4f7e-898d-b427f45925e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
