<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitOTPButton-TC-Login</name>
   <tag></tag>
   <elementGuidId>8ff14efe-b118-4b6f-9812-79b51f5f1d67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24c7f7af-bbbd-4ff9-b918-85c816215630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>2aa51b44-53af-446e-9ba6-982c5429d4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>30128aa7-6e73-4ecb-bc69-fb055787e087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>e594fa50-76d9-430b-9a07-e36a37036724</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>519e1015-ea45-415c-875d-936bf7969954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary text-white</value>
      <webElementGuid>1618f6a6-6a2e-4740-9ec0-26aff8302595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm:submitOTPButton&quot;)</value>
      <webElementGuid>124999d7-988b-42c5-9be1-7f0b40f5739a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>39802429-a08a-4aa7-99ca-03d4689891f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div[2]/div[3]/input</value>
      <webElementGuid>981ec076-dd53-4414-a94d-a76111854679</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>5a913855-4b7a-4636-933d-55a97d323d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MH360SmsloginForm:submitOTPButton' and @type = 'submit' and @name = 'MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>8dec3dca-0017-44aa-b0ae-07e4a402e202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
