<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitOTPButton-TC-LO</name>
   <tag></tag>
   <elementGuidId>970bd76d-a395-47f6-b79e-b63d5b494f38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b66e674-98e2-4bb0-b914-48fdfb9d464c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>7d01d481-3058-4843-9771-2333afbd8152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>442bb72c-d7fe-4e01-b626-faa69e0a15a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>587da886-626b-4602-a006-fee180dd924f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>00dfd851-baba-4718-824f-3a489b5d6cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary text-white</value>
      <webElementGuid>8da7e09d-145c-4f98-b1f0-ee3fa43ef5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm:submitOTPButton&quot;)</value>
      <webElementGuid>d120ec9c-ed7f-4890-8235-ed4a4505dbd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>3ecebc58-9a0b-4908-b3f4-484c70331c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div[2]/div[3]/input</value>
      <webElementGuid>c0726ea7-f3e4-42c8-bef6-74e675ad0881</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>d451f7f9-7462-4f74-ad26-da66e6ccf6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MH360SmsloginForm:submitOTPButton' and @type = 'submit' and @name = 'MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>0ab6d4e7-a518-43a7-89c1-a53ff9326d90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
