<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>submitOTPButton-TC-UI</name>
   <tag></tag>
   <elementGuidId>f6db19cc-519f-455c-bccc-f966ccb0f04a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46799903-cd5b-4359-90a7-c501b14bf998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>abb0df40-28e4-4089-a57f-733a03bc888e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fba70c68-b365-430f-a907-d10a0d12fd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MH360SmsloginForm:submitOTPButton</value>
      <webElementGuid>464eef36-bfd7-4969-8d44-957650295fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>22d2e819-5c3f-4d62-a841-8699d4bfedc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-lg btn-primary text-white</value>
      <webElementGuid>c3099be7-e2b3-40e8-921f-8740f01610cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MH360SmsloginForm:submitOTPButton&quot;)</value>
      <webElementGuid>62770c59-b65b-4f80-af17-5b1025771701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>9c4f4dd3-8104-4179-9ef8-28b01403c0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MH360SmsloginForm']/div[2]/div[3]/input</value>
      <webElementGuid>3c0f8412-37c7-48e2-97b5-48bda63c8f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>b96e582b-7e63-41b5-bed6-7f23beb20bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MH360SmsloginForm:submitOTPButton' and @type = 'submit' and @name = 'MH360SmsloginForm:submitOTPButton']</value>
      <webElementGuid>49925cd9-b89c-4979-9ffc-6bc86a79b5ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
