<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Login_circle text-center</name>
   <tag></tag>
   <elementGuidId>bb97d1fa-c8eb-4032-8133-df3665cd5cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cover-spin']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.circle.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ba25aad-bf91-418c-b48b-237849a4de14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>circle text-center</value>
      <webElementGuid>8e377a91-7e85-4052-83c5-e4704d2381d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cover-spin&quot;)/div[@class=&quot;circle text-center&quot;]</value>
      <webElementGuid>c9bef433-2071-4b62-b41c-5c316940a053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cover-spin']/div</value>
      <webElementGuid>b6ff6cf5-3f85-4c26-b381-dbd6bcd13371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::div[1]</value>
      <webElementGuid>6b4d23e9-186d-4216-97b9-e636d9dae770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>cfa825dd-0355-4bc7-8ece-426228cb078e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
