<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_login-mh360-image</name>
   <tag></tag>
   <elementGuidId>5341f15d-4d79-4140-9ed8-03e437648907</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='login-mh360-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-mh360-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af1f23c5-2647-4832-9edd-52a3abbe71bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-mh360-image</value>
      <webElementGuid>e52fb410-53fd-4cbe-9e55-f801cfe89e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/oxauth/ext/resources/images/logo-mh360.png</value>
      <webElementGuid>77bd3022-68e5-486c-a6d0-529fff0ecbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>95a2e499-78b0-4325-8d5a-fca5fafaa1a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mt-4</value>
      <webElementGuid>797e6029-bd25-456f-8157-a695bdb87e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-mh360-image&quot;)</value>
      <webElementGuid>e6d6162e-710b-427c-aefd-17671f7f75dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='login-mh360-image']</value>
      <webElementGuid>f16ba9ac-dd33-42b7-bb1e-a119f8a191ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>a3130b20-b5b8-4f8f-b9dc-dde45e74987f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'login-mh360-image' and @src = '/oxauth/ext/resources/images/logo-mh360.png']</value>
      <webElementGuid>257f4fc6-b5cd-40ad-b4a9-36a9e263504d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
