<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login-mh360-image-TC-LO</name>
   <tag></tag>
   <elementGuidId>649ca41d-d2cb-4c6f-ad7d-b70b6ce159d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='login-mh360-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#login-mh360-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9da1e175-df0e-49a8-b8ec-4bbd1f897c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login-mh360-image</value>
      <webElementGuid>e95bedb9-ae83-4924-b949-8a7fec3e8273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/oxauth/ext/resources/images/logo-mh360.png</value>
      <webElementGuid>52104959-04a7-465d-a8ff-fc7773ef70fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>e886b745-9707-4b1a-bf2d-df7eb6911dae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-2 mt-4</value>
      <webElementGuid>725bae0d-870c-4b63-8cc2-63d53c239ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-mh360-image&quot;)</value>
      <webElementGuid>3ce984b4-b4d4-4356-b4bc-70e682c679f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='login-mh360-image']</value>
      <webElementGuid>f2f39a58-18f3-43b8-b1e1-2e70aabbff90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>4a36c1f3-7dd5-4303-ac14-94969132996c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'login-mh360-image' and @src = '/oxauth/ext/resources/images/logo-mh360.png']</value>
      <webElementGuid>b39707aa-63b6-459b-9261-236203053761</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
