<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update User Information</name>
   <tag></tag>
   <elementGuidId>a14c6edb-b36b-4a77-96bc-a07f8c438b41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.mb-3.d-flex.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b1d668a7-5abf-4ee4-92da-10b55cc586b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce62641f-39d4-4e0f-bf4e-2ebee69ad74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mb-3 d-flex align-items-center</value>
      <webElementGuid>702e4942-fab0-4c18-833c-d01c2251b62e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update User Information </value>
      <webElementGuid>a7aae549-daf8-48bc-b43d-8f685d481499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-7 col-lg-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn btn-primary mb-3 d-flex align-items-center&quot;]</value>
      <webElementGuid>02813539-9591-4220-bbc8-903b6295aff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>eb9a22bd-0816-4978-9649-036c04ebc30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/div/div/a/div/button</value>
      <webElementGuid>71728da2-a160-4620-91c6-c84d76fb0fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Password'])[1]/preceding::button[1]</value>
      <webElementGuid>d78041c2-0aa2-41be-abbe-3d3cb631c97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5d6b0c8a-156e-4085-9edc-0feb08a0e75d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Update User Information ' or . = ' Update User Information ')]</value>
      <webElementGuid>fcd3d4db-1040-41ee-a508-a8f99027837b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
