<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout-TC-LO</name>
   <tag></tag>
   <elementGuidId>337c3ec3-43fb-425a-bba8-092983ace22e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b03aeff7-4e3b-40e0-a205-e9cece26085d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d890269b-0e8c-4721-903f-8c769e21b4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mb-3 d-flex align-items-center</value>
      <webElementGuid>4a92281f-04d2-4ee8-a02e-7728424a8f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Logout </value>
      <webElementGuid>e84f1a71-f484-426c-8ca5-1cdbeb3941a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-7 col-lg-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-grid&quot;]/button[@class=&quot;btn btn-primary mb-3 d-flex align-items-center&quot;]</value>
      <webElementGuid>420553fb-3860-42f3-8673-b7447b954a8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>5a18654a-b93c-46e1-bd91-e1b41b4b45d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/div/div/a[3]/div/button</value>
      <webElementGuid>3bfac66d-a4c8-4b45-a0c1-252fc046155a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Password'])[1]/following::button[1]</value>
      <webElementGuid>bfea98c1-7314-4ac1-8ac4-47164b69b089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update User Information'])[1]/following::button[2]</value>
      <webElementGuid>ce1ef9a7-1847-48d7-b84c-b4ccd0ae7850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/div/button</value>
      <webElementGuid>25e235fb-2264-4d3a-beb1-4d9401e6b838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Logout ' or . = ' Logout ')]</value>
      <webElementGuid>f165a8bf-ce32-48c2-8220-4eee87074d5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
