<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button-TC-UM</name>
   <tag></tag>
   <elementGuidId>ed35a5c9-c18c-4633-9f59-5e9db3d68b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.mb-3.d-flex.align-items-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ba6ac25-9fe7-4be3-bf89-41283f024168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a17db645-e87a-4d81-a8db-4e4e7d5b0215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mb-3 d-flex align-items-center</value>
      <webElementGuid>0b766c94-d6a3-4dad-91fd-93e0b2378502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Update User Information </value>
      <webElementGuid>77e8beb5-2ee0-489e-80b2-dcb0e81cd7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-7 col-lg-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn btn-primary mb-3 d-flex align-items-center&quot;]</value>
      <webElementGuid>1234f683-7352-4052-93d8-dee037797454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>60584793-2b46-4a00-bf48-d109a2bb0585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/div/div/a/div/button</value>
      <webElementGuid>5b2eaf88-f12a-4be5-a33b-3efd2384b281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Password'])[1]/preceding::button[1]</value>
      <webElementGuid>b880a638-4110-4777-9bc9-13fe4d3f31ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>555b09b2-0272-46e9-9db1-4cc44bd6976e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = ' Update User Information ' or . = ' Update User Information ')]</value>
      <webElementGuid>8fff8a9d-335c-4b9f-9736-0be6e4ac5743</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
