<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Update User Information_fas fa-user-edit _28b7f9</name>
   <tag></tag>
   <elementGuidId>d9cd5340-78b0-4b67-a9fb-1e34ad317961</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='landingPage']/div/div/a/div/button/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-user-edit.fa-fw.w-25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>62414a70-9a19-4c3b-84de-75bd6f5c2181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-user-edit fa-fw w-25</value>
      <webElementGuid>6c48b09b-bbb4-4d22-b377-f56df043b914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-7 col-lg-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn btn-primary mb-3 d-flex align-items-center&quot;]/i[@class=&quot;fas fa-user-edit fa-fw w-25&quot;]</value>
      <webElementGuid>e682ee0a-a4c4-4195-8edb-0afed0b85272</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/div/div/a/div/button/i</value>
      <webElementGuid>58c01626-2ded-425a-9970-e29a00aee6a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>013e7f74-93a8-4894-bf04-869f2faa99e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
