<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>landingPage-TC-UM</name>
   <tag></tag>
   <elementGuidId>0ea1eb0e-94de-4f07-94ee-1924078d92c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.mb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>327cf604-a6aa-46cd-9dfa-83957471ba93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo.svg</value>
      <webElementGuid>4d7b3c68-5598-4e05-af92-8d6e770e6d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid mb-4</value>
      <webElementGuid>418df180-cacf-4b19-9cf9-bfc7861a0069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/img[@class=&quot;img-fluid mb-4&quot;]</value>
      <webElementGuid>c5e778d4-db47-47b8-9fa9-6e63d06cf07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/img</value>
      <webElementGuid>69f3ca59-13c7-4105-b2b7-3400b95e9f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>ac957e1f-5b82-46f8-b2d8-8733684bf0fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/logo.svg']</value>
      <webElementGuid>21faf265-bd2d-43d1-beab-b5a033a24317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
