<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>landingPage-TC-UI</name>
   <tag></tag>
   <elementGuidId>f568737d-a42d-4ef0-84f8-2f00fa95e8d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='landingPage']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.mb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>65f93b7b-e423-44a9-b9b4-2f0534fa6742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/logo.svg</value>
      <webElementGuid>9d978911-a992-4339-badc-f92224e52544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid mb-4</value>
      <webElementGuid>623c661b-cabf-4fff-b1f0-3eef2d26711d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/img[@class=&quot;img-fluid mb-4&quot;]</value>
      <webElementGuid>419827ad-5001-423d-9980-5df2d18d3fae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/img</value>
      <webElementGuid>811a9ed0-aa4e-4fc3-a1bf-060577fb7a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>6288862e-8b5b-412a-90df-9b2436d61922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/logo.svg']</value>
      <webElementGuid>6305edcd-d0af-4dc9-8198-7b422ce62ab6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
