<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Update User Information</name>
   <tag></tag>
   <elementGuidId>0c3a406b-26af-4703-8ef8-dd0cbf4fb8f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='landingPage']/div/div/a/div/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.w-75</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>db77b4ca-e183-49ae-b85b-ac965055bd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-75</value>
      <webElementGuid>5c88224b-aacb-499e-b05b-f934e1072044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update User Information</value>
      <webElementGuid>0ade7718-e281-4a56-90bb-08b98420dfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landingPage&quot;)/div[@class=&quot;row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-7 col-lg-5&quot;]/a[@class=&quot;text-decoration-none&quot;]/div[@class=&quot;d-grid mt-3&quot;]/button[@class=&quot;btn btn-primary mb-3 d-flex align-items-center&quot;]/span[@class=&quot;w-75&quot;]</value>
      <webElementGuid>2a002a86-b515-4cde-b0f9-e3381f38ee4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='landingPage']/div/div/a/div/button/span[2]</value>
      <webElementGuid>a8cef023-e14c-4310-9b6b-2ea34ba61a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Password'])[1]/preceding::span[2]</value>
      <webElementGuid>1044bf15-13fc-443d-be9a-ebd685b43b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::span[4]</value>
      <webElementGuid>b0eb84b8-834f-4844-ab88-a1d438636240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update User Information']/parent::*</value>
      <webElementGuid>71706ecf-52cc-452b-aab9-f3d693ec6ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>227dab33-4491-4f48-a398-3a515e36127f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Update User Information' or . = 'Update User Information')]</value>
      <webElementGuid>538e5011-1612-4d8d-bd0a-37204c547959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
