<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Resend the OTP to my mobile phone in 51</name>
   <tag></tag>
   <elementGuidId>fc15a30e-4deb-48aa-a1d1-00f9422a5919</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='countdownID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#countdownID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e1d67d5-754d-4c6a-9828-22df2623af70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>countdownID</value>
      <webElementGuid>a980c2e2-1df3-407c-a1e7-d698703ee67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-13px text-secondary-dark-grey text-center mt-3</value>
      <webElementGuid>fbcab740-5645-4122-a521-ea86bea3db97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Resend the OTP to my mobile phone in: 51.
                        </value>
      <webElementGuid>88cc6116-d8c5-4bc9-a284-512797bb9edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;countdownID&quot;)</value>
      <webElementGuid>f3a4781d-4ccf-461c-83d3-f38ac2225efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='countdownID']</value>
      <webElementGuid>e6d98d32-40e9-4df9-8f3b-d4917d5e58cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp-phone']/div/div[2]/div</value>
      <webElementGuid>d81a6725-e518-432c-9164-baaa6d5088f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/following::div[5]</value>
      <webElementGuid>d0db9dd1-a85f-47dc-a49e-752b0b9c5ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[7]</value>
      <webElementGuid>f96cb689-fbd3-4f1d-8948-f8104510c201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::div[1]</value>
      <webElementGuid>2f25d946-7e10-43b0-9f6a-0270b4e28d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Resend the OTP to my mobile phone in: 51.']/parent::*</value>
      <webElementGuid>0b02eca8-1563-4bbe-966c-396a563f8761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div</value>
      <webElementGuid>661c801d-62d6-4a2e-803e-cbd423c4e8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'countdownID' and (text() = '
                            Resend the OTP to my mobile phone in: 51.
                        ' or . = '
                            Resend the OTP to my mobile phone in: 51.
                        ')]</value>
      <webElementGuid>1b598e70-55e5-4a22-8f37-f977bc19609b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
