<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_You may have entered an invalid pin, pl_5b384d</name>
   <tag></tag>
   <elementGuidId>c608b2e4-9b27-4566-b7fe-83f38371ab5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uss-alert-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-alert-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>625fd03c-21ca-4aa4-a914-94e4709325fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>64d3b7f6-539b-409c-8daf-ec79c81234ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-alert-error</value>
      <webElementGuid>58f01b30-c0f1-42c0-aa74-56ea2c92d777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger alert-dismissible fade alert-error show</value>
      <webElementGuid>33182f36-9cfa-472c-a7f3-6f06dd4e23fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> You may have entered an invalid pin, please try keying in the OTP again or request a new one</value>
      <webElementGuid>629edd7e-0d32-4afb-83cf-899f98f9786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-alert-error&quot;)</value>
      <webElementGuid>ce3c7f21-6671-4aa5-ae5c-583cf31f2530</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uss-alert-error']</value>
      <webElementGuid>82fff139-39f0-45cb-be73-4d61e471b30b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='otp']/div/div[2]/div</value>
      <webElementGuid>e52ade1a-887c-4e13-83ba-73776fb1f501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[2]</value>
      <webElementGuid>459acd7d-dadd-41ad-8800-3afc819365f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/preceding::div[1]</value>
      <webElementGuid>1f5f63c5-448d-43d1-879b-aaf21a986799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div</value>
      <webElementGuid>1e32e2db-1211-48f2-990c-fe4782843470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uss-alert-error' and (text() = ' You may have entered an invalid pin, please try keying in the OTP again or request a new one' or . = ' You may have entered an invalid pin, please try keying in the OTP again or request a new one')]</value>
      <webElementGuid>4cb1135e-4ad6-4ee2-bc6a-58fa20959a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
