<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_A one-time PIN has been sent via SMS to_be2b53</name>
   <tag></tag>
   <elementGuidId>84dc3917-2a76-4454-8a4b-3eac54a0bc21</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='OTPInput']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OTPInput</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d961721f-e57c-4621-8cc6-ad99cb5094ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OTPInput</value>
      <webElementGuid>6f8955ca-65be-47de-aa70-1f82723e2132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>digit-group-single flex justify-center pt-4 text-center</value>
      <webElementGuid>7a2da3cd-1008-405c-9a12-43d0412cf796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OTPInput&quot;)</value>
      <webElementGuid>43d9df9d-8dbe-4090-a8fc-9d00cf814e77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='OTPInput']</value>
      <webElementGuid>3a51ea28-5b52-4a55-97bb-b41ed71babea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp-phone']/div/div</value>
      <webElementGuid>d1119645-e30c-47a9-9d80-2f573ba7fbf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A one-time PIN has been sent via SMS to your mobile number'])[1]/following::div[3]</value>
      <webElementGuid>5a20fe35-cf4e-4f75-ba5d-483f78096dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your OTP'])[1]/following::div[5]</value>
      <webElementGuid>782c0277-b009-49d3-a48f-c384827911ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resend the OTP to my mobile phone in: 47.'])[1]/preceding::div[1]</value>
      <webElementGuid>97f4e557-58e5-4575-8b8e-fbe74ef36df7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verify'])[1]/preceding::div[3]</value>
      <webElementGuid>69551a68-9599-4a2b-a443-557e001929f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>329c0fa7-5bd5-4bda-8b0b-7ab9272310bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'OTPInput']</value>
      <webElementGuid>48e11e83-7af2-43ce-a5a5-96e1fd92c87a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
