<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Enter your OTP_uss-img-loader</name>
   <tag></tag>
   <elementGuidId>37fe10ba-3292-4de1-bfa4-8afd62a251bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='uss-img-loader']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-img-loader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>709ac687-8220-4a89-bfd3-7287e2c12bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/loader.gif</value>
      <webElementGuid>42d51952-e0d7-4b67-9208-9177201dad4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-img-loader</value>
      <webElementGuid>d2cb4fbc-1d90-4391-9cba-f4c1dc5be238</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-img-loader&quot;)</value>
      <webElementGuid>3ba5922a-a33b-45d4-b58e-1d1b77705152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='uss-img-loader']</value>
      <webElementGuid>22764cf7-7a57-4c6c-bf3a-21a4d4b13c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cover-spin']/div/img</value>
      <webElementGuid>dc243c21-637a-4889-a586-69b20a8e962c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f561a5c7-962a-4f02-9d62-45baddea9590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/loader.gif' and @id = 'uss-img-loader']</value>
      <webElementGuid>e354b67e-9619-41a3-8a9b-6b65b644dee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
