<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Verify_mx-auto</name>
   <tag></tag>
   <elementGuidId>401a5d70-b4e8-4011-9c95-e6540fbbe848</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3314e0c-953d-4edc-8caf-9a3d8c376f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>b52dd8b5-57a2-49f7-af81-7ea01debb06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3bcf4c25-6780-4f0d-9ce2-17dcec5910b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>1c5888de-101a-4d92-be7a-2c1862f318c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalSuccess&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]/img[@class=&quot;mx-auto&quot;]</value>
      <webElementGuid>19ac4969-f726-49bf-a1a4-628e05affe56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      <webElementGuid>9f5878f7-e015-49f7-9732-69df06fe73e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>07a1d611-cfc5-46e0-b65b-468f436ede8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg']</value>
      <webElementGuid>67ebfc1d-ba48-45ce-9149-c970e7b7fcbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
