<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modalSuccess-TC-UM</name>
   <tag></tag>
   <elementGuidId>fd0ad656-8779-47d7-aff0-6956efbc0429</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0da67e4e-9010-4973-8f86-a4dde66559c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>46a9b7bc-65d6-4b20-9ca5-e0c02cd7739f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3bacfec0-29ee-43f3-ad55-e24328e5f205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>542eb45e-7cc5-41b1-8ad3-37e03d7cabbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalSuccess&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]/img[@class=&quot;mx-auto&quot;]</value>
      <webElementGuid>be1e9aed-0c2a-4245-8023-448b5a006f75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      <webElementGuid>ff3faf75-61e8-4a6f-b74f-abd6d6fd2149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>65b1debb-8208-42ca-ac88-f19b80fc319e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg']</value>
      <webElementGuid>8e6095db-284f-42b2-a0ce-778f0e42ef2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
