<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Change Password</name>
   <tag></tag>
   <elementGuidId>c1135df6-bc40-449e-ad2f-5388d832ffc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='uss-text-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-text-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>844c6d5b-2aeb-4d10-975b-5fd10bb36b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-text-title</value>
      <webElementGuid>a34bdf30-0a07-4e77-83d8-d41039773eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 text-28 fw-mh color-black</value>
      <webElementGuid>bc5fe8e3-ac32-4f08-9712-ef3ca84dc865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change Password</value>
      <webElementGuid>02b57552-5562-4e6a-ab34-4a5c9fa69c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-text-title&quot;)</value>
      <webElementGuid>c7f382f1-a796-4fd4-adcc-5575763136d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='uss-text-title']</value>
      <webElementGuid>1cbcc927-8d70-4fb3-8532-fddbcca8165c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manage-password']/div/div/div/h1</value>
      <webElementGuid>b1ca59b3-596b-4bc9-9e9f-7579373dd9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't reuse a password from another account!')])[1]/preceding::h1[1]</value>
      <webElementGuid>62d28663-591b-4a1d-b894-f4d5078a2f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to make strong passwords'])[1]/preceding::h1[1]</value>
      <webElementGuid>2b4bd2ce-7d4a-4cce-abf8-147a79c9169d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c3802a46-6a61-4142-bcd5-81b0cc6335df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'uss-text-title' and (text() = 'Change Password' or . = 'Change Password')]</value>
      <webElementGuid>6a2b1b48-9073-442b-88ff-a95c29d24602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
