<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manage-password-TC-PR</name>
   <tag></tag>
   <elementGuidId>5584b1d8-a250-489d-90ba-f8ac0a317ff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='uss-text-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-text-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>59028094-8f0f-4ca8-b83d-312539cdb2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-text-title</value>
      <webElementGuid>48111003-68d7-4ce8-8041-df8b43037dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 text-28 fw-mh color-black</value>
      <webElementGuid>801f1ebd-7c02-41bb-9b65-8a72af8a92fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change Password</value>
      <webElementGuid>5584003d-c9c3-4128-90b6-e1c7f69d8650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-text-title&quot;)</value>
      <webElementGuid>fe9a8b06-9ad4-4956-9f27-8db1e1751a77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='uss-text-title']</value>
      <webElementGuid>d7e5b188-5922-47f7-b138-afe156ee351c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manage-password']/div/div/div/h1</value>
      <webElementGuid>c432cc3c-eb2a-4114-9cc4-070d2f43db00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't reuse a password from another account!')])[1]/preceding::h1[1]</value>
      <webElementGuid>f4a33be8-977e-4224-a8d7-e1c47e3820c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to make strong passwords'])[1]/preceding::h1[1]</value>
      <webElementGuid>655a8705-57f4-4099-8fc1-9cf7cb5049d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>b035dc43-f8f1-4a4b-9bdb-bd13769a1736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'uss-text-title' and (text() = 'Change Password' or . = 'Change Password')]</value>
      <webElementGuid>bdea6d84-e4b2-4235-98de-810fbe66437c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
