<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>manage-password-Error-TC-PR</name>
   <tag></tag>
   <elementGuidId>0e25b1af-ece0-4642-b447-22554f86239d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='manage-password']/div/div[2]/form/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.bg-card.card-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f01d82e8-9721-4752-a1da-2f1bb23c7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body bg-card card-password</value>
      <webElementGuid>475736c5-a9ce-4fb4-89c9-b5cc057a6f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters</value>
      <webElementGuid>1d9ee3af-8424-4c9f-91ec-ac1c48a691cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manage-password&quot;)/div[@class=&quot;row wrapper-login&quot;]/div[@class=&quot;col-12 mb-5&quot;]/form[1]/div[@class=&quot;group mb-3&quot;]/div[@class=&quot;card bg-message&quot;]/div[@class=&quot;card-body bg-card card-password&quot;]</value>
      <webElementGuid>56f4714a-8dcd-4c95-9319-f219beb353f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manage-password']/div/div[2]/form/div[2]/div/div</value>
      <webElementGuid>7cdddbc3-5ae3-4d12-9ba4-633c1e29f992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Password'])[1]/following::div[3]</value>
      <webElementGuid>40706432-4146-478a-b974-54180b0c62be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to make strong passwords'])[1]/following::div[4]</value>
      <webElementGuid>d0624b3d-1bb6-4e64-baef-158745721a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>b946af5d-8cf1-45d3-8fdf-26d1e6410db8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters' or . = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters')]</value>
      <webElementGuid>22dcf468-e24c-4db3-bdf9-3d9a9a598558</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
