<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strongPass-TC-PR</name>
   <tag></tag>
   <elementGuidId>abbc5601-b7a9-4308-aeef-f60b7c3ec6b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='strongPass']/div/div/div[2]/div[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dh-link-bdr-btn-black</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c1367786-de96-4361-b0e5-d271a8862fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dh-link-bdr-btn-black</value>
      <webElementGuid>daccc0f0-1484-40d4-8ef5-20b821abc9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>11dac313-b5cf-4937-8212-ec54f71f2de0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>fd80b852-c8b6-4cc4-8618-d6abe136af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#makingStrongPass</value>
      <webElementGuid>f7c7a0ad-8faf-426b-8440-f4662378c190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to make strong passwords</value>
      <webElementGuid>12c50c21-dbcb-4829-989b-8460dd886297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;strongPass&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;m-0 text-15px fw-mh mb-3&quot;]/a[@class=&quot;dh-link-bdr-btn-black&quot;]</value>
      <webElementGuid>9dd6d4a8-cf15-4b20-b1ce-4b5e1d81b69c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='strongPass']/div/div/div[2]/div[3]/a</value>
      <webElementGuid>3c18df63-e3f4-4430-ab4b-464ad94b7620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'How to make strong passwords')])[2]</value>
      <webElementGuid>2a5b03af-bb26-4f17-be42-a711d316107e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A combination of lowercase and uppercase letters, numeric digits, and symbols'])[1]/following::a[1]</value>
      <webElementGuid>34104050-34ce-44e3-b036-322a978c3172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A mix of 8-30 characters'])[1]/following::a[1]</value>
      <webElementGuid>ec252797-790f-4103-bd20-a65d7a5d5e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Making Strong Passwords'])[1]/preceding::a[1]</value>
      <webElementGuid>1c56b7dd-8dd5-4079-9926-e738926fdd66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>c0ac0e6a-c817-4287-8f34-c4a445de46e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'How to make strong passwords' or . = 'How to make strong passwords')]</value>
      <webElementGuid>8a25c156-05b2-4975-89d9-249587f7f303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
