<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TCF_div_Password-meter</name>
   <tag></tag>
   <elementGuidId>ad4a08ce-c8e9-43ab-8ddb-72d199722db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='manage-password']/div/div[2]/form/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-body.bg-card.card-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7e256ba6-7f1b-42f8-9db8-bda79913e301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-body bg-card card-password</value>
      <webElementGuid>a2bf05b2-b72e-4dc4-9c63-94999c4d2e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters</value>
      <webElementGuid>78b9b8df-4bc8-4407-957c-adda355ebb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;manage-password&quot;)/div[@class=&quot;row wrapper-login&quot;]/div[@class=&quot;col-12 mb-5&quot;]/form[1]/div[@class=&quot;group mb-3&quot;]/div[@class=&quot;card bg-message&quot;]/div[@class=&quot;card-body bg-card card-password&quot;]</value>
      <webElementGuid>4e429671-1326-4a68-9c0b-41f0d2169f78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manage-password']/div/div[2]/form/div[2]/div/div</value>
      <webElementGuid>78141732-fdf5-4437-8f7d-95cab51a9841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Password'])[1]/following::div[3]</value>
      <webElementGuid>e8699a14-d631-492c-98fa-1329d5665ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How to make strong passwords'])[1]/following::div[4]</value>
      <webElementGuid>86f3a01a-a22e-41a8-9469-2f9a32948c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div</value>
      <webElementGuid>1292554d-3272-4328-8873-9454f70b830b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters' or . = 'Your password should have:   At least one number  At least one uppercase and one lowercase letter  At least one special character  Minimum 8 characters')]</value>
      <webElementGuid>9a43e440-ed48-487d-a343-b25e82e25023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
