<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uss-img-modal-success-TC-PR</name>
   <tag></tag>
   <elementGuidId>869de908-37dc-47d3-9a7f-885d00bd3215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='uss-img-modal-success']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-img-modal-success</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a7821b4c-db46-4bcf-8465-6f0f1994bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>c1309b5b-fda8-4634-8ae4-57972ff2c3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>7ba2ac2a-2aca-44e2-91fd-9c6880c72982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>b59afede-115b-4bed-86a2-863d9186a57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-img-modal-success</value>
      <webElementGuid>837ee5d6-02bd-41e8-adce-cc0ca95e5f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-img-modal-success&quot;)</value>
      <webElementGuid>6c28621c-b0ae-43f4-b5e5-ed06d96aa856</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='uss-img-modal-success']</value>
      <webElementGuid>c5be07bb-12c2-4787-afcb-cbdc43d0e657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      <webElementGuid>2eac9efb-fc53-480a-ae40-d4e5dd618424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>4d05052a-551e-473e-ae87-fe39663c978e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg' and @id = 'uss-img-modal-success']</value>
      <webElementGuid>1c246fe4-e442-41eb-94a1-44c1b24b3e7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
