<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uss-changepassword-note-text-TC-PR</name>
   <tag></tag>
   <elementGuidId>1010e19d-579d-4171-a3d9-075bfa4b56d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='uss-changepassword-note-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-changepassword-note-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>83eb8b9c-167f-4b28-ae3b-0b00bd304677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3d413ea0-0b44-4e6e-a01a-a48a0eb7d478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#strongPass</value>
      <webElementGuid>4a97a60a-0715-4bab-a967-616feb4e0579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-changepassword-note-text</value>
      <webElementGuid>8cec4a08-d995-423c-95a6-c88ace5b052b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dh-link-bdr-btn</value>
      <webElementGuid>382e38ef-5a0b-479c-95b7-bee2f59e9a50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to make strong passwords</value>
      <webElementGuid>daed9863-b1b1-4614-a8c8-aa3e20ca5204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-changepassword-note-text&quot;)</value>
      <webElementGuid>4c000ee2-8f94-4435-a1ce-abba6061c681</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='uss-changepassword-note-text']</value>
      <webElementGuid>f5c7ad44-ecfb-406d-8f31-3889140efdc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='manage-password']/div/div[2]/div[2]/div/a</value>
      <webElementGuid>d4beb642-82cb-45d1-8c88-3a0cf517d666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'How to make strong passwords')]</value>
      <webElementGuid>3cf96770-64f7-4429-a997-354b6b4b792a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't reuse a password from another account!')])[1]/following::a[1]</value>
      <webElementGuid>00a9b1d2-e496-4f0d-8bb1-44a3fb98f0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[2]/following::a[1]</value>
      <webElementGuid>1e79c746-3b5e-4d8c-bbcc-7006c353ec2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Password'])[1]/preceding::a[1]</value>
      <webElementGuid>89afd606-0c49-4b25-8244-e21f09915a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm New Password'])[1]/preceding::a[1]</value>
      <webElementGuid>60e3546a-af1b-4e2c-98fd-a5e84c93ea4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='How to make strong passwords']/parent::*</value>
      <webElementGuid>ad618da5-bd03-4272-8af3-c8b50ac94637</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>30447746-c817-49f7-ad13-be49308a328a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'uss-changepassword-note-text' and (text() = 'How to make strong passwords' or . = 'How to make strong passwords')]</value>
      <webElementGuid>79381694-59fd-47a0-a0d2-aba4f499f1aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
