<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update information</name>
   <tag></tag>
   <elementGuidId>12d11db3-4c1f-4f81-ae98-b461cd99dd5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='uss-btn-submit1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-btn-submit1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8aa51af6-4cc7-4bf9-befb-72a280b12356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>ca846aaf-8f87-45d3-aaa0-2f24165a95b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-btn-submit1</value>
      <webElementGuid>a96b73e9-dfd9-4590-a557-f39aac96d777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white mx-auto col-10</value>
      <webElementGuid>9dcbdbee-ec48-42a0-8615-943b992f18dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update information
                            </value>
      <webElementGuid>43425a9b-17bf-4f80-9e3c-ca5eeaafe0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-btn-submit1&quot;)</value>
      <webElementGuid>5a69e940-f7e7-4726-bd03-dabaafb661a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='uss-btn-submit1']</value>
      <webElementGuid>a22909fa-62e9-4b05-a131-6c806e94185d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[9]/button</value>
      <webElementGuid>10b7f7d8-48bf-48bc-a9f0-65e0027414ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show additional information'])[1]/following::button[1]</value>
      <webElementGuid>e767fc65-dad6-4852-82e9-69400e8fa274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zimbabwe'])[2]/following::button[2]</value>
      <webElementGuid>6ec79ae0-e5d4-40e1-8dcc-3aa38564a9c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile Number'])[1]/preceding::button[1]</value>
      <webElementGuid>4b15f9c0-e0eb-4c71-8f62-cd4154c9f916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your new mobile number to receive a one-time passcode for validation'])[1]/preceding::button[1]</value>
      <webElementGuid>5ae1b3a0-67ae-4ac0-9ca8-72718eb33629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update information']/parent::*</value>
      <webElementGuid>4246de51-aa94-4704-b621-b2c78285c406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/button</value>
      <webElementGuid>481a8ec2-d363-484c-bb0f-cda316aca10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'uss-btn-submit1' and (text() = 'Update information
                            ' or . = 'Update information
                            ')]</value>
      <webElementGuid>28392622-63db-408d-ad62-0de48f71fcd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
