<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SingaporeIndonesiaMalaysiaAfghanistanla_43d1cf</name>
   <tag></tag>
   <elementGuidId>6612e67a-f6aa-4fff-9494-6609ca31676b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[5]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.group.group-country > div.input-group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4be78607-73fc-4710-b05c-a3785b39a4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group</value>
      <webElementGuid>9613fa58-720f-4372-9c7a-ac42465e1631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SingaporeIndonesiaMalaysiaAfghanistanÅland IslandsAlbaniaAlgeriaAlgeriaAmerican SamoaAndorraAngolaAnguillaAntarcticaAntigua And BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBhutanBolivia, Plurinational State OfBonaire, Sint Eustatius And SabaBosnia And HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurundiCambodiaCameroonCanadaCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCroatiaCubaCuraçaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGazaGazaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuineaGuinea-BissauGuyanaHaitiHeard Island And Mcdonald IslandsHoly See (Vatican City State)HondurasHong KongHong KongHungaryIcelandIndiaIndonesiaIran, Islamic Republic OfIraqIrelandIsle Of ManIsraelItalyIvory CoastIvory CoastJamaicaJapanJerseyJordanKazakhstanKenyaKirghiziaKirghiziaKiribatiKiribatiKorea, Democratic People's Republic OfKorea, Republic OfKosovoKuwaitLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacao SarMacao SarMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritiusMayotteMexicoMicronesia, Federated States OfMicronesia, Federated States OfMicronesia, Federated States OfMidway IslandsMidway IslandsMidway IslandsMoldova, Republic OfMonacoMongoliaMontenegroMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth MacedoniaNorth MacedoniaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarRéunionRomaniaRussian FederationRwandaSaint BarthélemySaint Helena, Ascension And Tristan Da CunhaSaint Kitts And NevisSaint LuciaSaint Pierre And MiquelonSaint Vincent And The GrenadinesSamoaSan MarinoSao Tome And PrincipeSaudi ArabiaSenegalSerbia/MontenegroSerbia/MontenegroSeychellesSierra LeoneSingaporeSint Maarten (Dutch Part)SlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia And The South Sandwich IslandsSouth SudanSpainSri LankaSudanSurinameSvalbard And Jan MayenSwazilandSwazilandSwedenSwitzerlandSyrian Arab RepublicTaiwan, Province Of ChinaTajikistanTanzania, United Republic OfThailandTimor-LesteTimor-LesteTogoTokelauTongaTrinidad And TobagoTunisiaTurkeyTurkmenistanTurks And Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUnited States Minor Outlying IslandsUpper VoltaUpper VoltaUruguayUzbekistanVanuatuVenezuela, Bolivarian Republic OfVietnamVirgin Islands, BritishVirgin Islands, U.S.Wallis And FutunaWestern SaharaYemenZaireZaireZambiaZimbabwe</value>
      <webElementGuid>ca46654b-0ae3-4cd6-8a66-51a9c5496936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateUserInfo&quot;)/div[@class=&quot;d-flex layout-box&quot;]/div[@class=&quot;col mx-auto&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row wrapper-login&quot;]/form[@class=&quot;mb-4&quot;]/div[@class=&quot;group group-country&quot;]/div[@class=&quot;input-group&quot;]</value>
      <webElementGuid>ee51fb73-5073-42a8-ba89-5397ac4e3a5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[5]/div</value>
      <webElementGuid>f36053b2-c357-4080-8601-330f746e8374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country of Residence'])[1]/following::div[1]</value>
      <webElementGuid>cf779deb-0105-42ac-82f4-848bea1a7af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[5]</value>
      <webElementGuid>9994bac0-4180-43d1-8a7c-1998c9af2f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div</value>
      <webElementGuid>bf95bc31-c3c2-4696-ab6e-352b185bcf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;SingaporeIndonesiaMalaysiaAfghanistanÅland IslandsAlbaniaAlgeriaAlgeriaAmerican SamoaAndorraAngolaAnguillaAntarcticaAntigua And BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBhutanBolivia, Plurinational State OfBonaire, Sint Eustatius And SabaBosnia And HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurundiCambodiaCameroonCanadaCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCroatiaCubaCuraçaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGazaGazaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuineaGuinea-BissauGuyanaHaitiHeard Island And Mcdonald IslandsHoly See (Vatican City State)HondurasHong KongHong KongHungaryIcelandIndiaIndonesiaIran, Islamic Republic OfIraqIrelandIsle Of ManIsraelItalyIvory CoastIvory CoastJamaicaJapanJerseyJordanKazakhstanKenyaKirghiziaKirghiziaKiribatiKiribatiKorea, Democratic People&quot; , &quot;'&quot; , &quot;s Republic OfKorea, Republic OfKosovoKuwaitLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacao SarMacao SarMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritiusMayotteMexicoMicronesia, Federated States OfMicronesia, Federated States OfMicronesia, Federated States OfMidway IslandsMidway IslandsMidway IslandsMoldova, Republic OfMonacoMongoliaMontenegroMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth MacedoniaNorth MacedoniaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarRéunionRomaniaRussian FederationRwandaSaint BarthélemySaint Helena, Ascension And Tristan Da CunhaSaint Kitts And NevisSaint LuciaSaint Pierre And MiquelonSaint Vincent And The GrenadinesSamoaSan MarinoSao Tome And PrincipeSaudi ArabiaSenegalSerbia/MontenegroSerbia/MontenegroSeychellesSierra LeoneSingaporeSint Maarten (Dutch Part)SlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia And The South Sandwich IslandsSouth SudanSpainSri LankaSudanSurinameSvalbard And Jan MayenSwazilandSwazilandSwedenSwitzerlandSyrian Arab RepublicTaiwan, Province Of ChinaTajikistanTanzania, United Republic OfThailandTimor-LesteTimor-LesteTogoTokelauTongaTrinidad And TobagoTunisiaTurkeyTurkmenistanTurks And Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUnited States Minor Outlying IslandsUpper VoltaUpper VoltaUruguayUzbekistanVanuatuVenezuela, Bolivarian Republic OfVietnamVirgin Islands, BritishVirgin Islands, U.S.Wallis And FutunaWestern SaharaYemenZaireZaireZambiaZimbabwe&quot;) or . = concat(&quot;SingaporeIndonesiaMalaysiaAfghanistanÅland IslandsAlbaniaAlgeriaAlgeriaAmerican SamoaAndorraAngolaAnguillaAntarcticaAntigua And BarbudaArgentinaArmeniaArubaAustraliaAustriaAzerbaijanBahamasBahrainBangladeshBarbadosBelarusBelgiumBelizeBeninBermudaBhutanBolivia, Plurinational State OfBonaire, Sint Eustatius And SabaBosnia And HerzegovinaBotswanaBouvet IslandBrazilBritish Indian Ocean TerritoryBrunei DarussalamBulgariaBurundiCambodiaCameroonCanadaCape VerdeCayman IslandsCentral African RepublicChadChannel IslandsChannel IslandsChileChinaChristmas IslandCocos (Keeling) IslandsColombiaComorosCook IslandsCosta RicaCroatiaCubaCuraçaoCyprusCzech RepublicDenmarkDjiboutiDominicaDominican RepublicEcuadorEgyptEl SalvadorEquatorial GuineaEritreaEstoniaEthiopiaFalkland Islands (Malvinas)Faroe IslandsFijiFinlandFranceFrench GuianaFrench PolynesiaFrench Southern TerritoriesGabonGambiaGazaGazaGeorgiaGermanyGhanaGibraltarGreeceGreenlandGrenadaGuadeloupeGuamGuatemalaGuernseyGuineaGuinea-BissauGuyanaHaitiHeard Island And Mcdonald IslandsHoly See (Vatican City State)HondurasHong KongHong KongHungaryIcelandIndiaIndonesiaIran, Islamic Republic OfIraqIrelandIsle Of ManIsraelItalyIvory CoastIvory CoastJamaicaJapanJerseyJordanKazakhstanKenyaKirghiziaKirghiziaKiribatiKiribatiKorea, Democratic People&quot; , &quot;'&quot; , &quot;s Republic OfKorea, Republic OfKosovoKuwaitLaosLatviaLebanonLesothoLiberiaLibyaLiechtensteinLithuaniaLuxembourgMacao SarMacao SarMadagascarMalawiMalaysiaMaldivesMaliMaltaMarshall IslandsMartiniqueMauritiusMayotteMexicoMicronesia, Federated States OfMicronesia, Federated States OfMicronesia, Federated States OfMidway IslandsMidway IslandsMidway IslandsMoldova, Republic OfMonacoMongoliaMontenegroMontserratMoroccoMozambiqueMyanmarNamibiaNauruNepalNetherlandsNew CaledoniaNew ZealandNicaraguaNigerNigeriaNiueNorfolk IslandNorth MacedoniaNorth MacedoniaNorthern Mariana IslandsNorwayOmanPakistanPalauPanamaPanamaPapua New GuineaParaguayPeruPhilippinesPitcairnPolandPortugalPuerto RicoQatarRéunionRomaniaRussian FederationRwandaSaint BarthélemySaint Helena, Ascension And Tristan Da CunhaSaint Kitts And NevisSaint LuciaSaint Pierre And MiquelonSaint Vincent And The GrenadinesSamoaSan MarinoSao Tome And PrincipeSaudi ArabiaSenegalSerbia/MontenegroSerbia/MontenegroSeychellesSierra LeoneSingaporeSint Maarten (Dutch Part)SlovakiaSloveniaSolomon IslandsSomaliaSouth AfricaSouth Georgia And The South Sandwich IslandsSouth SudanSpainSri LankaSudanSurinameSvalbard And Jan MayenSwazilandSwazilandSwedenSwitzerlandSyrian Arab RepublicTaiwan, Province Of ChinaTajikistanTanzania, United Republic OfThailandTimor-LesteTimor-LesteTogoTokelauTongaTrinidad And TobagoTunisiaTurkeyTurkmenistanTurks And Caicos IslandsTuvaluUgandaUkraineUnited Arab EmiratesUnited States Minor Outlying IslandsUpper VoltaUpper VoltaUruguayUzbekistanVanuatuVenezuela, Bolivarian Republic OfVietnamVirgin Islands, BritishVirgin Islands, U.S.Wallis And FutunaWestern SaharaYemenZaireZaireZambiaZimbabwe&quot;))]</value>
      <webElementGuid>15920bd2-0af4-4eaf-a099-ee384436db5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
