<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Female</name>
   <tag></tag>
   <elementGuidId>fe3fef0e-2762-410f-9454-3590e873d6a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='uss-text-value-gender-female']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-text-value-gender-female</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8dae78e0-b01b-49ef-80d6-edf914ba4274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-text-value-gender-female</value>
      <webElementGuid>cd718ce6-0695-41ec-bbc0-5c8b999404b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>box-disabled border-primary fw-mh d-flex flex-column justify-content-center align-items-center</value>
      <webElementGuid>0302caf9-9252-47f0-8543-287d9ef5f86c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Female</value>
      <webElementGuid>d6bb2387-232c-4aa2-b209-342560b3963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-text-value-gender-female&quot;)</value>
      <webElementGuid>e5b8e0b3-754d-4d77-85c9-c9112d352647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='uss-text-value-gender-female']</value>
      <webElementGuid>48b6baa4-1038-4524-bb97-c50779509fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[3]/div/label[2]/div/div</value>
      <webElementGuid>e4e375b7-a183-4055-974d-ef3704bd66f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::div[2]</value>
      <webElementGuid>2788c1b4-b564-4862-9f0f-d2dadbb5ea62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/following::div[5]</value>
      <webElementGuid>5be2a462-4e26-4d59-b438-3b705a219ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/preceding::div[1]</value>
      <webElementGuid>cdf57e52-2c77-436d-b909-37faecae9be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/div</value>
      <webElementGuid>f8f73c6c-5d96-424f-a0e5-04975a9d19b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'uss-text-value-gender-female' and (text() = 'Female' or . = 'Female')]</value>
      <webElementGuid>675bdc65-9b9e-42bc-b4fc-ce9abfd2a453</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
