<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_62</name>
   <tag></tag>
   <elementGuidId>6173f3dc-9178-4e19-beb9-c5aee24d404d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[12]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.group.group-phoneNumber > div.input-group > div.iti.iti--allow-dropdown.iti--separate-dial-code > div.iti__flag-container > div.iti__selected-flag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e8b9c4d3-4722-4921-a6f5-1dee472ac461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__selected-flag</value>
      <webElementGuid>ab46c9c9-6ccc-41ad-bf0a-48ccb28ebc26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>f17fb169-41c1-490f-aac2-bcb60a5596f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>iti-2__country-listbox</value>
      <webElementGuid>b91e5aa8-e7c1-45ac-bb89-2721d6bf3fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9b487be0-fcbd-4d14-b776-be26fd37ae16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>db6b35e9-0529-4e6a-85fa-c580ea7ad391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Indonesia: +62</value>
      <webElementGuid>e23f2a6c-6b51-455c-9dbd-7154d69a7a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>iti-2__item-id-preferred</value>
      <webElementGuid>074b6056-bbcc-47c0-940d-1f838e83801d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+62</value>
      <webElementGuid>9264e04f-6ef0-4d3f-9824-c8b31565209f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updateUserInfo&quot;)/div[@class=&quot;d-flex layout-box&quot;]/div[@class=&quot;col mx-auto&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row wrapper-login&quot;]/form[@class=&quot;mb-4&quot;]/div[@class=&quot;group group-phoneNumber&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/div[@class=&quot;iti__flag-container&quot;]/div[@class=&quot;iti__selected-flag&quot;]</value>
      <webElementGuid>3340b0f3-4030-4d46-a177-2f511bee59c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[12]/div/div/div/div</value>
      <webElementGuid>3235ebb4-6cde-4042-a69c-a65e5ce6beff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile No.'])[1]/following::div[4]</value>
      <webElementGuid>0d55a477-d922-4d46-8acb-35a210eeee87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter your new mobile number to receive a one-time passcode for validation'])[1]/following::div[5]</value>
      <webElementGuid>55a3980a-3f2b-438f-b72b-f77665101496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[5]/preceding::div[6]</value>
      <webElementGuid>d2020a43-57e8-4853-b617-ef3c11302c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[5]/preceding::div[8]</value>
      <webElementGuid>4ca55eac-d2fe-409d-a90c-66c3172b5c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/div</value>
      <webElementGuid>61ac985a-8a87-4f8a-b362-56129f4d7bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Indonesia: +62' and (text() = '+62' or . = '+62')]</value>
      <webElementGuid>595e4a0f-2522-4132-b50a-9d662cc5bac0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
