<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_65</name>
   <tag></tag>
   <elementGuidId>333b5585-acec-434c-af12-57243aff2183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collapseOne']/div/div[5]/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.iti__selected-flag</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ee195f2b-78a6-447f-8a70-bba3198c1aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__selected-flag</value>
      <webElementGuid>c84bd02e-44b7-4d9e-a9ab-e25e74a6362c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7f90963f-4b84-485e-bda8-6797e80d9be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>iti-5__country-listbox</value>
      <webElementGuid>63d0b0a8-794a-40c7-87de-78ac9494471a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd4eaaf6-7021-4860-9e53-2043eebcf302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e1c2e30-9af3-4f07-9f76-2717f8a2788f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Singapore: +65</value>
      <webElementGuid>a3882881-e87c-4436-b7e0-9fa875bcf0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>iti-5__item-sg-preferred</value>
      <webElementGuid>14ffb27c-88ac-4511-9979-09454e52b76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>+65</value>
      <webElementGuid>c433c040-7c07-4d53-a39e-5c5d3a526162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapseOne&quot;)/div[@class=&quot;card-body&quot;]/div[@class=&quot;group group-phoneEmergency&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;iti iti--allow-dropdown iti--separate-dial-code&quot;]/div[@class=&quot;iti__flag-container&quot;]/div[@class=&quot;iti__selected-flag&quot;]</value>
      <webElementGuid>38f71e8c-6e4e-45cb-a8b6-12cbf49f14bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collapseOne']/div/div[5]/div/div/div/div</value>
      <webElementGuid>85a5d438-7937-423f-9b61-47f6a4fd773a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phone number'])[1]/following::div[4]</value>
      <webElementGuid>539f1d31-45b1-4ea0-96fd-b6b7ff585205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::div[6]</value>
      <webElementGuid>07a32a13-8d26-44bc-86d7-e14f130425c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[3]/preceding::div[6]</value>
      <webElementGuid>b356903c-6cc6-4ddb-8949-9a83c1eae7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia'])[3]/preceding::div[8]</value>
      <webElementGuid>f16b599b-da82-41fb-9fb1-d3abcaabe338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div/div/div/div</value>
      <webElementGuid>6f8f4f18-f5c3-4617-9815-944a17fe57b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Singapore: +65' and (text() = '+65' or . = '+65')]</value>
      <webElementGuid>f4ded0d9-f2d3-4956-a9f3-4aaeb87398d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
