<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Date of Birth_toggle-btn-calender</name>
   <tag></tag>
   <elementGuidId>c211ac2d-11ee-4eb3-8993-6c170ec31655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='toggle-btn-calender']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#toggle-btn-calender</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>88cc4405-736d-4ed0-8768-da744bdfef62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/calender-icon.svg</value>
      <webElementGuid>f63f3991-5d80-4779-bd7b-348fa61e9119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toggle-btn-calender</value>
      <webElementGuid>bdbc97c7-984b-4fe4-be10-d1c30cac27d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calender icon</value>
      <webElementGuid>81c5891e-20b3-4d49-9505-7af26d5afa1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>9b732f8a-ede1-427a-a59c-ce5d7749fcf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toggle-btn-calender&quot;)</value>
      <webElementGuid>3ebfe3a8-593e-44b3-9cc1-b7900148f3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='toggle-btn-calender']</value>
      <webElementGuid>53b683e7-b8b5-4286-bf69-2923e0b53f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[4]/div/div[2]/img</value>
      <webElementGuid>6a1d2fc2-c066-4146-825a-f2347a568e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calender icon']</value>
      <webElementGuid>6d290ed4-90b1-4b29-a442-00202c92f3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>386d5254-c8d7-46a0-9a3e-ab18e37411b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/calender-icon.svg' and @id = 'toggle-btn-calender' and @alt = 'Calender icon']</value>
      <webElementGuid>16cf4b5a-0106-4842-922e-275d8436c817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
