<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wrong ID may result in missing result_4434a7</name>
   <tag></tag>
   <elementGuidId>20846c38-5247-4d0d-bae0-7c70aefe9e0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='IdentificationNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdentificationNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9566216b-5fc6-4840-bb1c-0970e4c5e22a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c710b2b2-41e5-439a-850a-809870287630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.g.S1234567A</value>
      <webElementGuid>f9cb3d4b-6d77-43da-b1a9-0e02e7e4a945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdentificationNumber</value>
      <webElementGuid>caf3f5b6-42d4-406c-8b96-f5e934474626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdentificationNumber</value>
      <webElementGuid>35a46af7-fd83-43d6-8989-c9fc8493b815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>e1a81022-6d73-4892-ae3b-3ee50d60611b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdentificationNumber&quot;)</value>
      <webElementGuid>565997cd-26b9-48c0-b028-95b51fb0eedd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='IdentificationNumber']</value>
      <webElementGuid>1043618b-6545-4492-83e3-4bd74a94f45e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[7]/div/div/div[2]/input</value>
      <webElementGuid>1353a283-34e7-4850-b8c6-c523bb9e700e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>751e7313-22f7-4fe6-bca6-8b750db3a723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'E.g.S1234567A' and @name = 'IdentificationNumber' and @id = 'IdentificationNumber']</value>
      <webElementGuid>a0908947-7748-45ce-9b11-2d9b68a1e0ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
