<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_dateOfBirth</name>
   <tag></tag>
   <elementGuidId>fface812-87f6-4f90-afeb-435f08da6b63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dateOfBirth']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dateOfBirth</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c87a4e2-a5f3-43b6-a5b7-759615b444b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>7d3cce81-3d72-41af-a31f-630fb1bd300f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2022-10-24</value>
      <webElementGuid>78e9a77d-a0cd-4983-988b-b8fa743458c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900-01-01</value>
      <webElementGuid>3d7f681f-7b3c-4fae-b020-f4e32f8ab8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>62e6ff6b-4e51-40a7-b192-71b388ea6ee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dateOfBirth</value>
      <webElementGuid>378b900d-3e5d-4b5f-a335-e8396908e8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>a34c6e5c-6f7f-4530-89c2-8d78de77ffc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5d174b10-b1f2-4789-a435-8f31c949c4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dateOfBirth&quot;)</value>
      <webElementGuid>3f2edad4-90c7-46dd-b16d-229b5f846fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dateOfBirth']</value>
      <webElementGuid>0cadb923-0fa8-4602-9b2a-34b83b3b4562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[4]/div/div/input</value>
      <webElementGuid>0772b71a-3d4b-4c72-befe-6082fae42f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>6d242b9d-cc33-42ad-925e-fc49a7b88988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dateOfBirth' and @placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>e2937562-7cc0-4e56-90eb-386b35ed7962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
