<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Indonesia62_1</name>
   <tag></tag>
   <elementGuidId>3faa754c-8508-4ecb-bd0d-20881468d3d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='iti-2__item-id-preferred']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iti-2__item-id-preferred</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d5c3f393-0b3e-4dd0-9c2c-3eff4bf215f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iti__country iti__preferred iti__active iti__highlight</value>
      <webElementGuid>a30b2212-1c8c-4e31-b273-ae9acd941d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>48dffcdd-7c27-4f12-b9b3-65a1164516a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iti-2__item-id-preferred</value>
      <webElementGuid>bb0b68ec-e517-4a59-97f0-163afd376691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>951d1ae6-c9b2-47bc-9b23-593c6118ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dial-code</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>314394db-456a-460a-a1ab-cf9f0256d79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-country-code</name>
      <type>Main</type>
      <value>id</value>
      <webElementGuid>509f5bb1-ab54-43a1-90fd-cf613c3ee7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e1bbe2f-f9c5-4bfb-ab80-0e7f25a0ae46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia+62</value>
      <webElementGuid>1a3694c5-7978-4182-b00e-34b5a7fcab32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iti-2__item-id-preferred&quot;)</value>
      <webElementGuid>40721d54-5797-4fff-bd1b-eb9a1ee76b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='iti-2__item-id-preferred']</value>
      <webElementGuid>d7407668-9ff5-4e54-8f14-77a6558336d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='iti-2__country-listbox']/li[2]</value>
      <webElementGuid>fe78760d-8b3f-4dc7-a1bd-d350435f9df0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Singapore'])[5]/following::li[1]</value>
      <webElementGuid>3b3b9868-912a-40e5-b2ed-f865334e880a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mobile No.'])[1]/following::li[2]</value>
      <webElementGuid>fe76ea8a-367c-48ef-8d81-7c25c7805483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Malaysia'])[5]/preceding::li[1]</value>
      <webElementGuid>6a4a6188-cfad-400e-99ca-f35f98f86c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/ul/li[2]</value>
      <webElementGuid>d93d74e4-a529-4182-8b10-d18d4b25bd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'iti-2__item-id-preferred' and (text() = 'Indonesia+62' or . = 'Indonesia+62')]</value>
      <webElementGuid>11e9285b-6be0-427b-b478-7f02aadfa82c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
