<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>modalSuccess-TC-UI</name>
   <tag></tag>
   <elementGuidId>760ea49a-d64d-4e7f-bdb4-ccbe6c8786ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mx-auto</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4b15d953-4597-46b6-99ae-839ecda88453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/success.svg</value>
      <webElementGuid>a7901ba3-d0df-4449-ae5f-a1773720d827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e764f667-b086-444a-9045-e527393ddbe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mx-auto</value>
      <webElementGuid>a395b440-70fe-45a5-bf4f-3bb0cc9d361f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalSuccess&quot;)/div[@class=&quot;modal-dialog modal-dialog-mh modal-dialog-centered mx-auto&quot;]/div[@class=&quot;modal-content modal-content-mh&quot;]/div[@class=&quot;modal-body text-center pb-5&quot;]/img[@class=&quot;mx-auto&quot;]</value>
      <webElementGuid>d35a3037-48d2-4b24-8f46-c85e9029f610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modalSuccess']/div/div/div[2]/img</value>
      <webElementGuid>f86dd12a-cf23-498a-9d24-b78ebb0fd426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/img</value>
      <webElementGuid>f13a5b67-3d2d-4cc9-9212-870790829be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/success.svg']</value>
      <webElementGuid>867c56a0-511b-4a15-9277-c58c3bedb89b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
