<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>phoneNumberUM</name>
   <tag></tag>
   <elementGuidId>f1d24ebb-0b82-4034-aa9f-ba39cf57f305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d22a9286-1658-44e7-b583-03261e40476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>087c6051-c5b7-472c-b3da-ac1dd5f34861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6c83be4-9879-4e3d-8697-7ebc05f768af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>a8357627-f03d-447a-8973-3a972952e16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-transparent-line form-control</value>
      <webElementGuid>53c99e55-c926-476e-8299-03a8ae5fcd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d1c54826-74f6-4675-ba72-060c87185aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-intl-tel-input-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5f5c4944-fc59-45d5-9bd8-400c5144b55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>812-345-678</value>
      <webElementGuid>ed625903-c376-42ef-8430-0c51efc9c66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumber&quot;)</value>
      <webElementGuid>23c569c4-1f60-412d-b223-69a2e7c8acdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNumber']</value>
      <webElementGuid>2d98e979-81ad-4aff-80b7-707eb1e8d390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[12]/div/div/input</value>
      <webElementGuid>b5cf8674-d6b6-4ef0-8dcc-1f5bb9c3ec28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/input</value>
      <webElementGuid>453df74b-78fc-4ba8-8f74-7cc6819fdd76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'phoneNumber' and @placeholder = '812-345-678']</value>
      <webElementGuid>044298bb-f483-4625-9ea3-5a145f4c9399</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
