<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_NRICFIN Passport</name>
   <tag></tag>
   <elementGuidId>0ec5a4d4-d517-40f8-a931-d5ba4c82adc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdentificationNumberType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdentificationNumberType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7b1bbdd3-6368-45c8-b4bf-bf8664e7ccc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IdentificationNumberCountry</value>
      <webElementGuid>bf22642c-a722-45e1-b33d-b65ac4faf758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdentificationNumberType</value>
      <webElementGuid>845dec6b-5676-460b-bede-5c5610d1da6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>ID Number</value>
      <webElementGuid>9775890d-54db-4587-9598-19b447b7f89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-select form-select-id-type</value>
      <webElementGuid>23424e62-5875-4da2-b613-22c1068e28ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NRIC/FIN Passport</value>
      <webElementGuid>97ef64d2-4ba5-47dc-a7e6-55e028b870ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdentificationNumberType&quot;)</value>
      <webElementGuid>2fa359c5-1e2d-46bb-8046-9f115993ac86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdentificationNumberType']</value>
      <webElementGuid>7c13b9cf-c111-4e8c-9e1c-982b0901d257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div[2]/form/div[7]/div/div/div/select</value>
      <webElementGuid>79ad155f-9f74-402a-928b-ca6356ff99a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wrong ID may result in missing results.'])[1]/following::select[1]</value>
      <webElementGuid>64b70d9d-d01a-4fe6-9e91-fbf322a12897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Number'])[1]/following::select[1]</value>
      <webElementGuid>8975c8ba-b0f1-4bce-8050-4234ee20a6c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::select[1]</value>
      <webElementGuid>bdbc83a7-3948-4435-9dae-d5ab7ffa7835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::select[1]</value>
      <webElementGuid>51976e39-a087-4e3b-8824-83d3a6f238eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>da7009b4-7526-4043-a690-bd5cde411641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'IdentificationNumberCountry' and @id = 'IdentificationNumberType' and (text() = 'NRIC/FIN Passport' or . = 'NRIC/FIN Passport')]</value>
      <webElementGuid>4d117278-49dd-4445-b20b-fa553114597b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
