<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uss-text-title-TC-UI</name>
   <tag></tag>
   <elementGuidId>d6cfd4dc-8686-4c0d-a83b-7bd5a3274984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='uss-text-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uss-text-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>24bebfc9-5482-428c-9c0d-fc1bfa654c22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uss-text-title</value>
      <webElementGuid>b7d89f01-0b5f-43e7-9e1a-cb84dd05f5de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 text-28px text-grey-dark</value>
      <webElementGuid>7c574e8a-5454-44a4-8d03-7694a70f540c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update Account Details</value>
      <webElementGuid>05b5dcfa-2479-4502-9274-87e6f68d43d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uss-text-title&quot;)</value>
      <webElementGuid>b8db4a7a-bcbb-47a2-a92c-a05200dec163</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='uss-text-title']</value>
      <webElementGuid>10b2ca44-31a3-4d0d-a94c-8037f5ae2d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='updateUserInfo']/div/div/div/div/h1</value>
      <webElementGuid>a6995c0e-a644-4024-8971-1ed083319ac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Information'])[1]/preceding::h1[1]</value>
      <webElementGuid>87c9c8be-f2a0-42d5-9e50-e743c319bb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[1]/preceding::h1[1]</value>
      <webElementGuid>f0a21851-dab2-4f3f-b98e-88161c94df74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Update Account Details']/parent::*</value>
      <webElementGuid>595178ea-ad70-4817-857c-bb7310dbc5f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>4ce9eb81-ae09-471d-a209-69f438e349a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'uss-text-title' and (text() = 'Update Account Details' or . = 'Update Account Details')]</value>
      <webElementGuid>c3832e88-2c5f-4ace-a01a-4026d42851ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
